# Generated by Django 3.2.25 on 2025-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('OHM', 'Ley de Ohm')], max_length=50)),
                ('etiqueta', models.CharField(help_text='Ej: Bomba Principal', max_length=200)),
                ('datos_entrada', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
