# Generated by Django 3.2.25 on 2025-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoras', '0002_alter_historialcalculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcalculo',
            name='tipo',
            field=models.CharField(choices=[('OHM', 'Ley de Ohm'), ('TRANSMISOR', 'Transmisor 4-20mA'), ('VIBRACION', 'Sonda de Vibración')], max_length=50),
        ),
    ]
