# Generated by Django 3.2.25 on 2025-11-26 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoras', '0003_alter_historialcalculo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcalculo',
            name='tipo',
            field=models.CharField(choices=[('OHM', 'Ley de Ohm'), ('TRANSMISOR', 'Transmisor 4-20mA'), ('VIBRACION', 'Sonda de Vibración'), ('CONVERSOR', 'Conversor Universal')], max_length=50),
        ),
    ]
